### ISSUE TITLE
Unknown column 'b.board_language'

### ISSUE THREAD

**Issue by dragomano** [SMFTricks/Language-Boards#2]
After installing the mod, I get this error after entering any board:

Unknown column 'b.board_language' in 'field list'
File: Subs-BoardIndex.php
Line: 108 

Fresh install, SMF 2.1.1, PHP 7.4.28, MariaDB 10.6.5, Language Boards v1.0.4

**Comment by DiegoAndresCortes** [comment]
That'd be https://github.com/SMFTricks/Language-Boards/blob/30e5317408012fbed16e15161c8ab14d5367302b/Sources/LanguageBoards.php#L184

I could not reproduce this issue yet.
Did you get the column created in the database?
Does it fix it using the plain name?

**Comment by dragomano** [comment]
Yes, `board_language` column exists.

**Comment by dragomano** [comment]
The same error with another fresh install, on PostgresQL 12.7. The `board_language` column in smf_boards exists.

**Comment by dragomano** [comment]
One more test forum, with MySQL 5.7 - no errors, everything works fine.

**Comment by DiegoAndresCortes** [comment]
I was able to reproduce on PG 13.2
I will investigate the issue

**Comment by DiegoAndresCortes** [comment]
Can you test the changes [#264706e7bcc733735c6bee3296e0c3a50ae77ce9](https://github.com/SMFTricks/Language-Boards/commit/264706e7bcc733735c6bee3296e0c3a50ae77ce9)

I'll wait for your feedback before tagging it as a release

**Comment by DiegoAndresCortes** [comment]
I forgot to remove b.board_name from the query will do later
Should I cache the added query if `lb_board_deny` is not enabled?

**Comment by dragomano** [comment]
Cache everything you can cache is useful :)
Yes, it works fine now.
